import { Dimensions } from "react-native";

export const DIMENSIONS = {
  WINDOW_HEIGHT: Dimensions.get("window").height,
  WINDOW_WIDTH: Dimensions.get("window").width,
};

export const SPACING = {
  sw10: DIMENSIONS.WINDOW_WIDTH / 30,
  sw15: DIMENSIONS.WINDOW_WIDTH / 25,
  sw20: DIMENSIONS.WINDOW_WIDTH / 19,
  sw25: DIMENSIONS.WINDOW_WIDTH / 14,
  sw30: DIMENSIONS.WINDOW_WIDTH / 8,

  sh2: DIMENSIONS.WINDOW_HEIGHT / 250,
  sh6: DIMENSIONS.WINDOW_HEIGHT / 120,
  sh15: DIMENSIONS.WINDOW_HEIGHT / 54,
  sh20: DIMENSIONS.WINDOW_HEIGHT / 50,
};

export const WIDTH = {
  w0: DIMENSIONS.WINDOW_WIDTH,
  w80: DIMENSIONS.WINDOW_WIDTH / 4.5,
  w155: DIMENSIONS.WINDOW_WIDTH / 2.2,
  w200: DIMENSIONS.WINDOW_WIDTH / 1.5,
  w250: DIMENSIONS.WINDOW_WIDTH / 1.3,
  w300: DIMENSIONS.WINDOW_WIDTH / 1.15,

};

export const HEIGHT = {
  h0: DIMENSIONS.WINDOW_HEIGHT,
  h24: DIMENSIONS.WINDOW_HEIGHT / 26,
  h36: DIMENSIONS.WINDOW_HEIGHT / 23,
  h45: DIMENSIONS.WINDOW_HEIGHT / 17,
  h140: DIMENSIONS.WINDOW_HEIGHT / 5.65,
  h144: DIMENSIONS.WINDOW_HEIGHT / 5.4,
  h174: DIMENSIONS.WINDOW_HEIGHT / 4.8,
  h270: DIMENSIONS.WINDOW_HEIGHT / 2.34,
};

export const FONTS = {
f12:  DIMENSIONS.WINDOW_HEIGHT * 0.014,
f15:  DIMENSIONS.WINDOW_HEIGHT * 0.018,
f18:  DIMENSIONS.WINDOW_HEIGHT * 0.020,
f29:  DIMENSIONS.WINDOW_HEIGHT * 0.034,



}


